### ISSUE TITLE
Question: why omit <body> and <head>?

### ISSUE THREAD

**Issue by rstacruz** [bendc/frontend-guidelines#19]
While they are not required in HTML5 anymore, many would argue that it's better to be explicit about these for clarity.

**Comment by bendc** [comment]
Less code makes code easier to read imho. No strong opinion on that one, but that's my preference :)

**Comment by NET4ORCE** [comment]
@rstacruz I struggle to concur with this too.  IMHO having the head/body is a clearer.  

I also have reservations around promoting the practice of dropping quotes for attributes.  Again, personally I find them easier to read.  But more than that - Consistency.  Having some with and some without is much worse in my eyes and I don't see any benefit to mixing them up.

The other question is around browser support.  Given that the lambda JavaScript example aren't   supported in any browser other than Firefox, I assume you've not any Cross compat testing @bendc ?  

Has anyone read research on the impact is caused by dropping `<head>` / `<body>` across the range of devices today?

**Comment by bendc** [comment]
In short:

* I don't "promote" a quote-free code -- there's no guideline about that.
* The whole document doesn't care about the current browser implementations. It's solely based on the standard specifications. (For JS, you can just easily transpile your ES2015 code using [Babel](http://babeljs.io)).
* Omitting `html`, `head` and `body` is valid and works on all modern browsers (I don't recommend dropping `html` though).

**Comment by zalog** [comment]
Take a look at DOM in ie9: http://imgur.com/bb4n6nB

**Comment by NET4ORCE** [comment]
Indeed, you don't explicitly "promote" a specific guideline regard quotes. 

However, please be aware that devs, most notably new devs, will infer conclusions from the examples, albeit where no conclusion was intended to be drawn.  Once their conclusion is drawn, be it "good" or "bad", they will blindly adhere to them without understanding possible consequences.  Possibly, unintentionally, propagating bad practices.  

By writing these best practices _please_ be aware of this and how statements / examples can be misinterpreted;   (Many new) Devs will automatically trust everything written; as great as brevity is, with code, consider the unintended consequences of not being explicitly clear.

**Comment by phanan** [comment]
:+1: It's a bit weird to me that you have this line in the JavaScript section (which I can't agree more):

> Don't obfuscate the intent of your code by using seemingly smart tricks.

and have the HTML code implicit in the name of brevity.

**Comment by agauniyal** [comment]
:+1: for @NET4ORCE and he is correct. Body and Head tags might not be necessary , but niether is a ' ; ' in css as you have already stated. They are mostly introduced for readablity purposes and a few new devs/designers might/will take your guidelines too strictly and get wrong message about using them. 

For me , I'll continue using html , head as well as body tags to maintain uniformity across a lot of websites until they're proven obsecure for use.

**Comment by Far0s** [comment]
@agauniyal <html> is still required if I'm not mistaken, and that's what Ben's guidelines are saying.

**Comment by agauniyal** [comment]
@Far0s sorry if I wasn't clear enough. I'm stating the need for `<body>`  `<html>`  `<head>` etc tags for readablity , consistency purposes 
``` HTML
<!-- good  but not good enough -->
<!doctype html>
<html lang=en>
  <meta charset=utf-8>
  <title>Contact</title>
  <link rel=stylesheet href=style.css>

  <h1>Contact me</h1>
  <label>
    Email address:
    <input type=email placeholder=you@email.com required>
  </label>
  <script src=main.js></script>
</html>
<!-- good  but not good enough -->
```

``` HTML
<!-- better -->
<!doctype html>
<html lang=en>
  <head>
      <meta charset=utf-8>
      <title>Contact</title>
      <link rel=stylesheet href=style.css>
  </head>
  <body>
      <h1>Contact me</h1>
      <label>
        Email address:
        <input type=email placeholder=you@email.com required>
      </label>
      <script src=main.js></script>
  </body>
</html>
<!-- good  but not good enough -->
```
 same as the author has stated about using ' ; ' in css.
> While the semicolon is technically a separator in CSS, always treat it as a terminator.

**Comment by Far0s** [comment]
@agauniyal Yes, I was not trying to prove you wrong, just making sure you didn't misunderstood yourself which tags were included here, my 1st message was probably vague :)
Even though I still don't have much experience in the matter, I have mixed feelings about both the semicolon in CSS and the head/body tags in HTML.

1/ I always thought the semicolon was mandatory in CSS, for me a CSS property without a semicolon at the end is just wrong CSS. But it's probably because everyone is saying it, it became jurisprudence I guess. (I have doubts now, it's mandatory right ?) So for me there's no point in arguing about the semicolon, because it's just good writing, not a matter of readability.

2/ While I see the importance of separating what is invisible to the client (the head) and what is visible to the client (the body), I think the fact that some elements of the code which are invisible to the client are in the body (at the end, for performance) proves that the head tag is not universal in the way that it should separate the visible from the invisible. 
Therefore, why should we try to store those script/link/meta/title tags into a head placed at the top, when they could be wherever they want, and we would just have to know by some other, simpler way that those tags won't be seen by the client.

Anyway, I might be writing garbage right now, so I will stop, that was just my honest thought.

**Comment by rstacruz** [comment]
semicolons are required in CSS except for the last property, which browsers are forgiving about. they're not optional (as in the case of JavaScript), they're simply errors that CSS parsers are forgiving about.

JavaScript semicolons, on the other hand, are an entirely different matter ;)

**Comment by bendc** [comment]
@rstacruz You're completely wrong. Please do some research before asserting things like that publicly.

**Comment by cornellsteven** [comment]
@bendc Wait... How exactly is @rstacruz  *completely wrong*? Semi-colons *are* required as delimiters between multiple declarations in CSS.

**Comment by bendc** [comment]
They're *not* "simply errors that CSS parsers are forgiving about".

**Comment by cornellsteven** [comment]
Okay, gotcha. I focused on the wrong thing :)

-- 
Cornell Campbell
cornellsteven@gmail.com

**Comment by anEffingChamp** [comment]
From what I can tell the goals in most projects are consistency, and simplicity. `<head>` and `<body>` are not required, so we can eliminate them for simplicity. We can potentially omit the last semicolon for simplicity, but some times semicolons are required in CSS, so we should strive to always use them for consistency. Some people may disagree, but those people can also subscribe to a different style guide.
