### ISSUE TITLE
Clarify or reconsider box model guideline

### ISSUE THREAD

**Issue by karlhorky** [bendc/frontend-guidelines#2]
Nice guide, most of the guidelines I find very good.

One thing I found peculiar was the box model guideline. This seems to go against industry standard, and is difficult to understand. For instance:

- http://www.paulirish.com/2012/box-sizing-border-box-ftw/
- http://css-tricks.com/box-sizing/
- http://blog.teamtreehouse.com/box-sizing-secret-simple-css-layouts

Do you know something I don't here?

**Comment by bendc** [comment]
Thanks!

I guess I should clarify this example. I’m mostly fine with a global `* { box-sizing: border-box; }`, I’m only opposed to changing the box model randomly. The example illustrates a bad usage where changing the box model to get a full-width element is fundamentally wrong (since it’s the default behavior of block elements anyway).

**Comment by karlhorky** [comment]
Right, okay, understood! Yeah that would be cool to have that clarified.

**Comment by NET4ORCE** [comment]
+1 - There's nothing wrong with `border-box` 

If you intended to cite changing box-model though the doc as bad then clarify that. 

Whereas, if your suggestion that `border-box` is bad please provide evidence; you'll find this hard as there is none. 

Personally, I've used 'border-box' for well over a decade & half; and I must admit can take offence against anyone suggesting 'border-box' is bad.  This stems from the zealots that would lurk in efnet #CSS IRC channel in the late 90's & early 00's refusing to help anyone until they moved their entire CSS to the "Standards" Box Model.  

I think it as a box model suffered, and thus the take up was much slower, because it was IE 5.5 default model - Of course, a browser these zealots had a hatred, despite it being the first to support XHR (AJAX).

</rant>

**Comment by jimniels** [comment]
Would love to see this clarification on the guidelines. When I read it, I wondered why it was there. Had to hunt down this explanation.

**Comment by lrobert** [comment]
+1 on the explanation. I've sent a PR to update it.

**Comment by NET4ORCE** [comment]
:+1:  Aye that's the ticket!

**Comment by karlhorky** [comment]
@lrobert Your PR is in your forked repo. I've opened a new PR in this repo with your changes here: https://github.com/bendc/frontend-guidelines/pull/16

**Comment by bendc** [comment]
[Fixed](https://github.com/bendc/frontend-guidelines#box-model). Thanks guys!

**Comment by lrobert** [comment]
Thanks @karlhorky
