### ISSUE TITLE
Avoid Curry vs. product.bind()...

### ISSUE THREAD

**Issue by davezuko** [bendc/frontend-guidelines#72]
You mention avoiding curry (which I highly disagree with) but you're essentially currying/partially applying in your example of:

```js
const product = (a, b) => a * b;
const triple = product.bind(null, 3);
```

If you were to follow your earlier guidelines, wouldn't this recommendation instead be:

```js
const product = (a, b) => a * b;
const triple = (a) => a * 3;
```
I agree that the first example is more elegant, but true currying is *even more so*. It might be more useful to say "don't abuse curry" than "strictly avoid it." I do agree with you that the following could be construed as unintuitive for the uninitiated:

```js
const sum = a => b => a + b;
sum(5)(3); // => 8
```

but that function definition does not implement true currying, as you are unable to fully supply the arguments in the initial call; it's essentially a poor-man's curry. If this were to be a proper curried function, you could do the following:

```js
const sum = curry((a, b) => a + b);
sum(1)(2); // 3
sum(1, 2); // 3

const add5 = sum(5);
add5(5); // 10
```

Is this not what you're striving for with elegance, composability, and reusability? I think this is a wonderful guide, but this suggestion in particular struck me as extremely out of place.

**Comment by bendc** [comment]
While I agree with you that currying might produce elegant solutions, I'm pretty sure it's better to avoid it overall. The example you provide, for example, could lead to inconsistent code where curried functions are sometimes called recursively, and sometimes not. And since the actual uses cases are so unusual, I'd prefer keeping this practice that confuses most developers out of my code :)
